pipeline {
    agent any

    environment {
        DOCKER_HOST = '127.0.0.1:2376'
    }

    stages {
        stage('prepare deps') {
            steps {
                sh 'make ci-build-image-base'
            }
        }
        stage('test') {
            steps {
                sh 'make tg-ci-run'
            }
        }
    }
}