# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='basics.Tag'),
        ),
    ]
