# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0003_contact_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='tags',
        ),
        migrations.AddField(
            model_name='contact',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='contacts', to='basics.Tag'),
        ),
    ]
