version: '3'

services:

  tests:
    image: mrupgrade/djl-base:latest
    command: make test
    volumes:
      - ../../:/src/
    environment:
      - DJL_DB_HOST=db
      - DJL_DB_PORT=5432
      - DJL_REDIS_HOST=cache
      - DJL_REDIS_PORT=6379
    depends_on:
      - db
      - cache
    user: ${USER_ID}


  db:
    image: postgres:9.6
    ports:
      - "5432"
    volumes:
      - ../pg_sql:/docker-entrypoint-initdb.d

  cache:
    image: redis:3
    ports:
      - "6379"
